[package]
name = "service-quotas"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
aws-config = "0.51.0"
aws-sdk-servicequotas = "0.21.0"
tokio-stream = "0.1.11"
aws-sdk-cloudwatch = "0.21.0"
chrono = "0.4.23"
clap = { version = "4.0.26", features = ["derive"] }
